Repository dispersal/CMPUT404-project-socialdistribution, pull requests merged in 2019-04, with the labels that each got.

#165 Bug/500 comment
  posts/helpers.py
  posts/models.py
  posts/serializers.py
  posts/viewsfolder/comment_views.py
Labels: bug

#169 Goes to the correct profile now.
  posts/viewsfolder/feed_views.py
Labels: bug, front end

#177 ✨Can view your friends in your profile✨
  posts/helpers.py
  posts/static/author/author-posts.css
  posts/templates/author/author_posts.html
  posts/viewsfolder/feed_views.py
  staticfiles/post/post.css
Labels: front end
